index:
  name:1.4 兑换区商品列表
  desc:兑换区商品列表
  method:get
  group:F
  order:F1.4
  params:
    tags:
      desc:标签id
      type:int
      require:0
      demoValue:1
      remark:用于推荐使用 1 即 新品推荐
    category_id:
      desc:分类ID
      type:int
      require:0
      demoValue:7
      remark:商品分类
    brand_id:
      desc:品牌ID
      type:int
      require:0
      demoValue:7
      remark:商品品牌
    point_id:
      desc:兑换点ID
      type:int
      require:0
      demoValue:1000000
      remark:从兑换点列表进来时传递 
    order_by:
      desc:排序方式
      remark:默认不传  销量 sf_exchange_product.sales 价格 sf_exchange_product.platform_price
    sort:
      desc:升序或者降序
      remark:1 降序  0 升序
      require:0  
    key:
      desc:关键词
      
  response:
    total:
      desc:总数量
      type:int
      require:1  
    list:
      desc:数据集
      type:array
      require:1
      item:
        product_id:
          desc:产品ID
          type:int
          require:1
        exchange_point_id:  
          desc:兑换点Id
          type:int  
          require:1
        stock:  
          desc:库存
          type:int  
          require:1
        product:
          desc:商品信息集合
          type:object
          require:1
          item:
            title:
              desc:产品名称
            sub_title:
              desc:产品子标题
            tags:
              desc:产品标签
              remark:标签串，以逗号连接 1-精品 2-热门 3-新品    
            coin:
              desc:省币
            limit:
              desc:限购数
            platform_price:
              desc:价格
            images:
              desc:相册集 里面src即为图片路径
              type:array
                      
details:
  name:1.5 商品详情
  desc:商品详情 需要传递产品ID 和 兑换点ID 在加入订单时需要对应到兑换点上
  method:get
  group:F
  order:F1.5
  params:
    point_id:
      desc:兑换点ID
      type:int
      require:1
      demoValue:1000000
      remark:
    product_id:
      desc:产品ID
      type:int
      require:1
      demoValue:3
      remark:
  response: 
    data:
      desc:数据集
      type:object
      require:1
      item:
        title:
          desc:名称
          type:string
          require:1
        sub_title:  
          desc:小标题
          type:string  
          require:1
        tags:
          desc:产品标签
          remark:标签串，以逗号连接 1-精品 2-热门 3-新品
        stock:  
          desc:库存
          type:string  
          require:1       
        coin:  
          desc:省币
          type:float  
          require:1
        platform_price:
          desc:平台价
          type:float  
          require:1  
        images:
          desc:相册
          type:array
          item:
            src:
              desc:路径      
sku:
  name:1.6 商品SKU
  desc:商品SKU
  method:get
  group:F
  order:F1.6
  params:
    id:
      desc:商品ID
      type:int
      require:0
      demoValue:3
      remark:
    point_id:
      desc:兑换点ID
      type:int
      require:0
      demoValue:3
      remark:
          
  response: 
    data:
      desc:数据集
      type:object
      require:1
      item:    
        sku_groups:
          desc:sku_groups key则为属性名 value为值
          type:array
sku-price:
  name:1.7 商品SKU价格
  desc:商品SKU价格
  method:get
  group:F
  order:F1.7
  params:
    id:
      desc:商品ID
      type:int
      require:0
      demoValue:4
      remark:
    key:
      desc:SKU组合值
      type:string
      require:1
      demoValue:15
      remark:
    point_id:
      desc:兑换点ID
      type:int
      require:0
      demoValue:1000000
      remark:  
  response: 
    data:
      desc:数据集
      type:object
      require:1
      item:
        old_price:
          desc:市场价
          type:float
          require:1
        price:
          desc:平台价
          type:float
          require:1
        stock:
          desc:库存
          type:int
          require:1
        coin:
          desc:省币
          type:int
          require:1
        id:
          desc:skuID
          type:int
          require:1
content:
  name:1.8 商品详情内容
  desc:商品详情内容
  method:get
  group:F
  order:F1.8
  params:
    product_id:
      desc:商品ID
      type:int
      require:0
      demoValue:3
    type:
      desc:类型（1手机端，2PC端）
      type:int
      require:0
      demoValue:1
  response:
    data:
      desc:数据集
      type:object
      require:1
      item:
        product_id:
          desc:商品ID
          type:int
          require:1
        simple_desc:
          desc:描述
          type:int
          require:1
        mobile_details:
          desc:移动端详情
          type:string
          require:N
        pc_details:
          desc:电脑端详情
          type:string
          require:N


  