index:
  name:1.2 在线商城商品列表
  desc:在线商城商品
  method:get
  group:D
  order:D1.2
  params:
    category_id:
      desc:分类ID
      type:int
      require:0
      demoValue:1
      remark: 
    merchants_id:
      desc:商户ID
      type:int
      require:0
      demoValue:1
    key:
      desc:关键字
      type:string
      require:0
      demoValue:美的
    order_by:
      desc:排序方式
      type:string
      require:0
      remark:综合排序[不传] 销量[sales] 价格[platform_price]
      demoValue:  
  response: 
    list:
      desc:数据集
      type:array
      require:1
      item:
        title:
          desc:商品名称
          type:name
          require:1
        sub_title:  
          desc:子标题
          type:string  
          require:1
        limit:
          desc:限购数
          type:int
          require:1
        market_price:
          desc:市场价
          type:float
          require:1
        stock:
          desc:库存
          type:int
          require:1    
        platform_price:
          desc:平台价
          type:float
          require:1  
        brand:
          desc:品牌信息
          type:object
          item:
            name:
              desc:品牌名称
        images:
          desc:相册
          type:object
          item:
            src:
              desc:路径
        merchants:
          desc:商户信息
          type:object
          item:
            is_platform:
              desc:是否自营    
basic:
  name:1.3 商城商品基本信息
  desc:商品基本信息
  method:get
  group:D
  order:D1.3
  params:
    id:
      desc:商品ID
      type:int
      require:0
      demoValue:8
      remark:
  response: 
    data:
      desc:数据集
      type:object
      require:1
      item:
        title:
          desc:商品名称
          type:name
          require:1
        sub_title:  
          desc:子标题
          type:string  
          require:1
        limit:
          desc:限购数
          type:int
          require:1
        market_price:
          desc:市场价
          type:float
          require:1
        platform_price:
          desc:平台价
          type:float
          require:1
        stock:
          desc:库存
          type:int
          require:1     
        images:
          desc:相册
          type:object
          item:
            src:
              desc:路径    
sku:
  name:1.4 商城商品SKU
  desc:商品SKU
  method:get
  group:D
  order:D1.4
  params:
    id:
      desc:商品ID
      type:int
      require:0
      demoValue:8
      remark:
  response: 
    data:
      desc:数据集
      type:object
      require:1
      item:    
        sku_groups:
          desc:sku_groups key则为属性名 value为值
          type:array
sku-price:
  name:1.5 商城商品SKU价格
  desc:商品SKU价格
  method:get
  group:D
  order:D1.5
  params:
    id:
      desc:商品ID
      type:int
      require:0
      demoValue:8
      remark:
    key:
      desc:SKU组合值
      type:string
      require:1
      demoValue:15,白色
      remark:
  response: 
    data:
      desc:数据集
      type:object
      require:1
      item:
        old_price:
          desc:市场价
          type:float
          require:1
        price:
          desc:平台价
          type:float
          require:1
        stock:
          desc:库存
          type:int
          require:1     
comments:
  name:1.6 商城商品评价
  desc:商品评价 支持分页通用参数
  method:get
  group:D
  order:D1.6
  params:
    id:
      desc:商品ID
      type:int
      require:0
      demoValue:6
      remark:
  response:
    total:
      desc:总条数
      type:int
      require:1     
    list:
      desc:数据集
      type:object
      require:1
      item:
        content:
          desc:内容
          type:string
          require:1
        ctime:
          desc:生成时间
          type:float
          require:1
        member:
          desc:用户信息集
          type:object
          require:1  
merchants:
  name:1.7 商城商品商家信息
  desc:商城商品商家信息
  method:get
  group:D
  order:D1.7
  params:
    merchants_id:
      desc:商户ID
      type:int
      require:0
      demoValue:1003302
      remark:从商品基本信息接口获取商户id
  response:   
    data:
      desc:数据集
      type:object
      require:1
      item:
        name:
          desc:商户名称
          type:string
          require:1
        extends:
          desc:扩展信息 包含店招logo
          type:float
          require:1
        feedback_rate:
          desc:好评率
          type:string
          require:1 
        focus:
          desc:关注数
          type:int
          require:1
        sell_counts:
          desc:在售商品数
          type:int
          require:1                    